spring.application.name=payment-service
spring.data.mongodb.uri=mongodb+srv://root:root@ctse-payment.wftqqy1.mongodb.net/payment?appName=ctse-payment&tlsAllowInvalidHostnames=true&tlsAllowInvalidCertificates=true
server.port=8082
