spring.application.name=PAYMENT-SERVICE
spring.data.mongodb.uri=mongodb+srv://root:root@ctse-payment.wftqqy1.mongodb.net/payment?appName=ctse-payment&tlsAllowInvalidHostnames=true&tlsAllowInvalidCertificates=true
server.port=8082
# Eureka Configuration
eureka.client.service-url.defaultZone=https://ctseserviceregistryapp.purplecoast-1718a0fd.centralindia.azurecontainerapps.io/eureka/
eureka.instance.prefer-ip-address=true